### ISSUE TITLE
[Bug] Plugin doesn't load when installed via BDCompat (Powercord)

### ISSUE THREAD

**Issue by Mr-Foxtrot** [Japanese-Schoolgirl/DiscordPlugin-CustomPanelForSendingPictures#1]
For [Powercord](https://powercord.dev/) there is a plugin to load BetterDiscord plugins within the client mod. However, powercord has different security restrictions unlike BetterDiscord. This may just be an error on the compatibility plugin, [BDCompat](https://github.com/Juby210/bdCompat) however I feel it has to do with how *your* plugin is coded.

In short, your plugin doesn't load in Powercord, it gives a "undefined" message in the console when trying to manually enable it.
![image](https://user-images.githubusercontent.com/45246118/100976389-704eee00-350d-11eb-96a7-00a50f330c30.png)

Could you update the plugin to work in Powercord in BDcompat?

**Comment by Japanese-Schoolgirl** [comment]
@Mr-Foxtrot From version 0.2.9 this problem should be resolved. Please check if your problem is resolved

**Comment by Mr-Foxtrot** [comment]
Alrighty! Just checked and the plugin now loads in Powercord! Thanks!
![image](https://user-images.githubusercontent.com/45246118/101129472-9b017b00-35cf-11eb-8092-097894593e55.png)
