### ISSUE TITLE
Incorrect folder slash on linux/unix

### ISSUE THREAD

**Issue by RhythmLunatic** [Japanese-Schoolgirl/DiscordPlugin-CustomPanelForSendingPictures#2]
The plugin uses \ instead of / so it breaks on Linux.
I don't know any js so I can't fix it but maybe there is something like OS.path.join() for JavaScript so it works regardless of platform.

Also the command for opening folders on Linux is `xdg-open`, it works if I change it at line 444.

P.S. I donated $5 on donationalerts, hopefully you see it. Cool plugin.

**Comment by Japanese-Schoolgirl** [comment]
Thank you <3

I don't use Linux, so it will take me longer to debug the problem. I will try to fix the problem in the next couple of days;
I will @ you when I'll post the next update

**Comment by Japanese-Schoolgirl** [comment]
At the moment I found another problem that has appeared with the new version of Discord Canary. The developers seem to have updated the "upload" module (on all versions) and I need to fix fresh problem of uploading pictures to Discord servers

The Linux folder support part is done, but the update will be delayed until the issue with the module is resolved

**Comment by Japanese-Schoolgirl** [comment]
@RhythmLunatic, I have released an update. Please let me know if it fixed your problems

**Comment by RhythmLunatic** [comment]
Yes, it works fine, thank you.
