### ISSUE TITLE
Plugin does not show on BDPlugins list

### ISSUE THREAD

**Issue by Yimellovzski** [Japanese-Schoolgirl/DiscordPlugin-CustomPanelForSendingPictures#3]
I did all the installation steps and repeated them a couple of times, as well as clearing the cache and still nothing. I even deleted a couple of plugins to see if there were conflicts and it still won't show, does it have something to do with my Powercord installation itself?

**Comment by Japanese-Schoolgirl** [comment]
@Yimellovzski, I have released an update that should fix it. Please let me know if it resolves your problem

**Comment by Yimellovzski** [comment]
> @Yimellovzski, I have released an update that should fix it. Please let me know if it resolves your problem

Thank you! It solved the problem now!
![DiscordCanary_IGzqKuV1vv](https://user-images.githubusercontent.com/45341995/165871785-f23581ca-f0ac-40c9-a15f-c6bb61cc717c.png)
